store:
  dsn: local-dev.db  # postgres example:  "host=myhost port=1433 user=username dbname=dbname password=mypassword"
  dialect: sqlite3  # supports sqlite3, mssql, mysql, postgres

server:
  port: 8888
  graceperiod: 3s  # number of seconds for graceful shutdown

redis:
  image: redis:5.0.4-alpine
  addr: localhost
  port: 6379
  DB: 0
  password: ""

# This should be the docker server settings for your private repository that
# are used to house the base images. i.e. the python runtime image
# If the username is empty, login is skipped.
docker:
  username: ""
  password: ""
  email: ""
  serveraddr: ""

registry:
  image: registry:2.7.1
  protocol: http
  domain: localhost
  port: 5000
  username: ""
  password: ""
