# this is only for local testing environment

version: '3.7'
services:
  registry:
    restart: always
    image: registry:2.7.1
    ports:
      - 5000:5000
    #    environment:
    #      REGISTRY_HTTP_ADDR: 0.0.0.0:443
    #      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    #      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    volumes:
      # using windows, but change this to whatever fits your needs
      - C:\\temp\\data:/var/lib/registry
#      - "./certs:/certs"
